"""add phone number column to users table

Revision ID: 324c3cc9577f
Revises: 1206ee543c88
Create Date: 2022-03-21 22:52:00.012158

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '324c3cc9577f'
down_revision = '1206ee543c88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_number', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone_number')
    # ### end Alembic commands ###
